name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: checkout env
      run: |
        echo $PWD
        ls -al
    - name: install sentry
      run: |
        ./install.sh --skip-user-prompt
    - name: check image
      run: |
        docker images ls
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag sentry:$(date +%s)
